---
- hosts: all
  become: yes
  tasks:
    - name: stop if variables are undefined
      fail: msg='check comments in group_vars/all and edit ~/.bash_profile'
      when: package_state is undefined or nvidia_driver is undefined or main_user is undefined

    - name: update apt cache
      apt: update_cache=yes

    - name: install kernel headers and build-essential
      apt: name={{ item }} state={{ package_state }}
      with_items:
        - linux-headers-{{ ansible_kernel }}
        - build-essential
        - dkms

    - name: install other useful packages
      apt: name={{ item }} state={{ package_state }}
      with_items:
        - cmake
        - g++
        - gfortran
        - git
        - swig
        - pkg-config
        - python-dev
        - python-pip
        - python-wheel
        - bc
        - gnuplot
        - software-properties-common
        - wget
        - htop
        - mc
        - debconf-utils
    
    - name: autoremove unused packages
      shell: apt-get -y autoremove
    
    - name: autoremove unused packages again
      shell: apt-get -y autoremove

    - name: run apt-get dist-upgrade
      apt: upgrade=dist
      when: "package_state == 'latest'"
      register: upgrade_contents

    - name: if kernel was upgraded in the dist-upgrade step, reboot
      shell: reboot
      when: "upgrade_contents is defined and upgrade_contents.stdout.find('linux-image') != -1"
