---
- hosts: all
  become: yes
  tasks:
    - include: checks.yml

    - name: add Nvidia drivers apt repository
      apt_repository: repo='ppa:graphics-drivers/ppa' update_cache=yes

    - name: install the ubuntu-drivers-common package
      apt: name=ubuntu-drivers-common state={{ package_state }}

    - name: download CUDA (may take a long time)
      get_url: url={{ cuda_url }} dest={{ packages_folder }}/{{ cuda_file }} force=no
      register: get_cuda

    - name: install CUDA (logs in /tmp/cuda*)
      shell: sh {{ packages_folder }}/{{ cuda_file }} --silent --toolkit --samples --verbose --override
      when: get_cuda|changed

    - name: downlod CUDA patch (may take a long time)
      get_url: url={{ cuda_patch1_url }} dest={{ packages_folder }}/{{ cuda_patch1_file }} force=no
      register: get_cuda_patch1

    - name: apply CUDA patch
      shell: sh {{ packages_folder }}/{{ cuda_patch1_file }} --silent --accept-eula
      when: get_cuda_patch1|changed

    - name: download cuDNN
      get_url: url={{ cudnn_url }} dest={{ packages_folder }}/{{ cudnn_file }} force=no
      register: get_cudnn

    - name: extract cuDNN
      unarchive: src={{ packages_folder }}/{{ cudnn_file }} dest={{ packages_folder }}/ copy=no
      when: get_cudnn|changed

    - name: copy cuDNN header file(s)
      shell: cp -d {{ packages_folder }}/cuda/include/cudnn.h /usr/local/cuda/include/
      when: get_cudnn|changed

    - name: copy cuDNN library files
      shell: cp -d {{ packages_folder }}/cuda/lib64/libcudnn* /usr/local/cuda/lib64/
      when: get_cudnn|changed

    - name: make sure cuDNN files have the right permissions
      shell: chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
      when: get_cudnn|changed

    - name: create CUDA_HOME and other variables
      template: src=cuda-home dest=/etc/profile.d/cuda-home.sh owner=root mode=0644
      when: get_cudnn|changed

    - name: download and install the Nvidia driver and dependencies
      apt: name={{ nvidia_driver }} state={{ package_state }}

    - name: install various useful libraries and packages
      apt: name={{ item }} state={{ package_state }}
      with_items:
        - freeglut3-dev
        - libglu1-mesa-dev
