---
- hosts: all
  become: yes
  tasks:
    - include: checks.yml

    - name: download TensorFlow
      get_url: url=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl dest=/root/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl force=no mode=0644
      register: get_tensorflow

    - name: install TensorFlow
      pip: name=/root/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl state={{ package_state }}
      when: get_tensorflow|changed

    - name: install extra libs for TF
      pip: name={{ item }} state={{ package_state }}
      with_items:
        - tflearn
