---
- hosts: all
  become: yes
  # ugly hack to provide same environment as /etc/profile.d/cuda-home.sh
  environment:
    CUDA_HOME: "{{ cuda_home }}"
    LD_LIBRARY_PATH: "{{ lookup('env', 'LD_LIBRARY_PATH') }}:{{ cuda_home }}/lib64"
    PATH: "{{ cuda_home }}/bin:{{ lookup('env', 'PATH') }}"
  tasks:
    - include: checks.yml

    - name: does {{ packages_folder }} exist
      file: path={{ packages_folder }} state=directory

    - name: clone/update TensorFlow repository
      git: repo=https://github.com/tensorflow/tensorflow dest={{ packages_folder }}/tensorflow
      register: get_tensorflow

    - name: stop here
      fail: msg="stop"

    - name: install TensorFlow
      pip: name=/root/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl state={{ package_state }}
      when: get_tensorflow|changed

    - name: install extra libs for TF
      pip: name={{ item }} state={{ package_state }}
      with_items:
        - tflearn
