---
- hosts: all
  become: yes
  tasks:
    - include: checks.yml
    
    - name: check if {{ main_user }} account is created
      shell: /usr/bin/getent passwd {{ main_user }} | /usr/bin/wc -l | tr -d ' '
      register: main_user_exists
      failed_when: "'0' in main_user_exists.stdout"

    - name: install Theano
      pip: name=Theano state={{ package_state }}
    
    - name: ensure .theanorc exists
      file: path=/home/{{ main_user }}/.theanorc state=touch owner={{ main_user }}
    
    - name: ensure [nvcc] exists in ~/.theanorc
      lineinfile: dest=/home/{{ main_user }}/.theanorc line="[nvcc]" state=present

# TODO: .theanorc
#[nvcc]
#flags = -arch=sm_30

# THEANO_FLAGS=device=gpu0 python check1.py
