---
- hosts: all
  become: yes
  tasks:
    - name: check if variables are defined
      fail: msg='define vars - package_state'
      when: package_state is undefined or main_user is undefined

    - name: install Theano
      pip: name=Theano state={{ package_state }}
    
    - name: ensure [nvcc] exists in ~/.theanorc
      lineinfile: dest=/home/{{ main_user }}/.theanorc line="[nvcc]" state=present

# THEANO_FLAGS=device=gpu0 python check1.py
