---
- hosts: all
  become: yes
  tasks:
    - name: check if variables are defined
      fail: msg='define vars - package_state'
      when: package_state is undefined

    - name: install Keras
      pip: name=Keras state={{ package_state }}
