---
- hosts: all
  become: yes
  tasks:
    - name: check if variables are defined
      fail: msg='check comments in group_vars/all and edit ~/.bash_profile'
      when: package_state is undefined

    - name: install Keras
      pip: name=Keras state={{ package_state }}
