---
- hosts: all
  become: yes
  tasks:
    - include: checks.yml

    - name: Enable the Octave repository
      apt_repository: repo='ppa:octave/stable'

    - name: Enable the R repository
      apt_repository: repo='ppa:marutter/rrutter'

    - name: update apt cache
      apt: update_cache=yes

    - name: Install Octave
      apt: name={{ item }} state={{ package_state }}
      with_items:
        - octave

    - name: Install R
      apt: name={{ item }} state={{ package_state }}
      with_items:
        - r-base

    - name: download and install RStudio
      apt: deb=http://download1.rstudio.org/rstudio-0.99.903-amd64.deb
